name: CI

on:
  push:
    branches:
      - main
      - dev-jin
      - dev-jun
      - dev-hyun
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci --include=optional

      - name: Build
        run: npm run build
